import type { TrainingScenario } from "./types";

export const TRAINING_SCENARIOS: Record<TrainingScenario["id"], TrainingScenario> = {
  "scandinavian-queen-chase": {
    id: "scandinavian-queen-chase",
    title: "Scandinavian: gain a tempo",
    summary: "After 1. e4 d5 2. exd5 Qxd5, White to move.",
    category: "opening",
    prompt: "Black has recovered the pawn with the queen. Find the forcing move that develops a piece and gains time on the queen.",
    fen: "rnb1kbnr/pppp1ppp/8/3q4/8/8/PPPP1PPP/RNBQKBNR w KQkq - 0 3",
    humanColor: "w",
    objective: "Develop with tempo against Black's exposed queen.",
    hints: ["Which White minor piece can develop immediately?", "Look at the knight on b1 and the queen on d5.", "Nc3 develops the knight and attacks Black's queen."],
    solution: { from: "b1", to: "c3", san: "Nc3" },
    success: "Nc3 develops with tempo and makes Black's queen move again.",
  },
  "italian-central-break": {
    id: "italian-central-break",
    title: "Italian: prepare the center",
    summary: "A quiet development position after 1. e4 e5 2. Nf3 Nc6 3. Bc4 Bc5.",
    category: "opening",
    prompt: "Finish your development plan with a move that supports the center and opens the dark-squared bishop's diagonal later.",
    fen: "r1bqk1nr/pppp1ppp/2n5/2b1p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4",
    humanColor: "w",
    objective: "Build a stable center before committing to tactics.",
    hints: ["Do not rush the attack while your king is still in the middle.", "Which pawn can support e4 without blocking a developed piece?", "d3 supports e4 and prepares a safe kingside plan."],
    solution: { from: "d2", to: "d3", san: "d3" },
    success: "d3 reinforces e4 and gives the Italian position a sound foundation.",
  },
  "knight-fork": {
    id: "knight-fork",
    title: "Knight fork: king and queen",
    summary: "White can use a knight jump to attack Black's king and queen at once.",
    category: "tactics",
    prompt: "Find the forcing knight move. It must check the king while also attacking the queen.",
    fen: "2k1q3/8/8/1N6/8/8/8/4K3 w - - 0 1",
    humanColor: "w",
    objective: "Spot a double attack before calculating material gains.",
    hints: ["A knight on d6 attacks both c8 and e8.", "Can the knight on b5 reach d6?", "Nd6+ checks the king and forks the queen on e8."],
    solution: { from: "b5", to: "d6", san: "Nd6+" },
    success: "Nd6+ is a clean fork: the king must answer the check and the queen is attacked.",
  },
  "mate-net": {
    id: "mate-net",
    title: "Mate net: seal the king",
    summary: "White has a one-move mating net with king-and-queen coordination.",
    category: "checkmate",
    prompt: "Deliver mate in one. Check every escape square and make sure the king cannot capture your queen.",
    fen: "6k1/5Q2/6K1/8/8/8/8/8 w - - 0 1",
    humanColor: "w",
    objective: "Use your king to protect the queen at close range.",
    hints: ["The black king is boxed in by the edge of the board.", "Your king on g6 protects g7.", "Qg7# covers h8 and cannot be captured."],
    solution: { from: "f7", to: "g7", san: "Qg7#" },
    success: "Qg7# is mate: the queen seals the flight squares and the king protects her.",
  },
};
